### ISSUE TITLE
unclear how to use this? 

### ISSUE THREAD

**Issue by nsteinme** [pozel/Neuropixel-2.0-IMRO-GUI#1]
Hi, just wanted to leave a note here to say that I tried out your software and thought it would be suitable for what I want to do, but was not able to understand how to use it. My goal was to manually pick a selection of 384 sites in a particular pattern, and generate an imro file for it. I'm not sure whether this is supposed to be possible - when I do "select channels" I can only highlight one red channel per channel group, and I'm not sure what that means. I didn't find any documentation about how to use this so please let me know if I missed it.

**Comment by pozel** [comment]
Hi! Thank you for reaching out -- I've been meaning to get back to this gui to add documentation. In the meantime, you should check out Charlie Walter's GUI (also another grad student at hopkins) [https://github.com/ckwalters/npx2_site_gui] --
